image: busybox:latest

stages:
  - build
  - test
  - deploy
variables:
  IMAGE_TAG: $CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA

cache:
  key:
    files:
      - composer.lock
  paths:
    - vendor/

build1:
  stage: build
  script:
    - echo "Do your build here"
    - echo one >> file1.txt
    - echo two >> file2.txt
    - mkdir -p vendor/
    - echo "build" > vendor/hello.txt
  artifacts:
    paths:
      - file1.txt
  

docker build:
# Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u $GITLAB_CI_USER -p $GITLAB_CI_PASSWORD $CI_REGISTRY
    - echo $GITLAB_CI_USER $GITLAB_CI_PASSWORD $CI_REGISTRY $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - echo "Hello from docker!" > from_docker.txt
  artifacts:
    paths:
      - from_docker.txt

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"
    - cat vendor/hello.txt
    - cat from_docker.txt
    # - grep one file1.txt
    # - sleep 20

test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"
    # - grep two file2.txt

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
  environment: production

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp file1.txt public/index.html
    - echo 404 >> public/404.html
  artifacts:
    exclude:
      - public/404.html
    paths:
      - public
  only:
    - main
