image: busybox:latest

stages:
  - build
  - test
  - deploy

build1:
  stage: build
  script:
    - echo "Do your build here"
    - echo one >> file1.txt
    - echo two >> file2.txt
    - echo three >> file3.txt
  artifacts:
    paths:
      - "file1.txt"
      - "file2.txt"
      - "file3.txt"
    expire_in: 30 days
    exclude:
      - /builds/ny7321711/ny/file3.txt

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"
    - grep one file1.txt

test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"
    - grep two file2.txt

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
  environment: production

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp file1.txt public/index.html
  artifacts:
    paths:
      - public
  only:
    - main
